### ISSUE TITLE
[Feature request] Create possibility to send multiple queries at once.

### ISSUE THREAD

**Issue by Tomen** [graknlabs/grakn-node#5]
Right now, there is no possibility to have transactions with grakn-node. This can create problems when I want to perform multiple queries like an atomic operation.

One possible way to work around this problem would be to send multiple queries with one request. However, when I try this, the server would return an error. I have dug into the code of the REST API server and I think I found a possibility to send multiple queries at once.

The corresponding line at the server side is this one: https://github.com/graknlabs/grakn/blob/93f2e17d57a7a6355ed4d8bbe5df081220034a47/grakn-engine/src/main/java/ai/grakn/engine/controller/GraqlController.java#L161

The corresponding param is defined as "multi" here: https://github.com/graknlabs/grakn/blob/master/grakn-core/src/main/java/ai/grakn/util/REST.java#L101

So it looks like it would be sufficient to set the param "multi" to "true" and then send multiple queries at once.

I will try to implement this feature and then send a pull request.

**Comment by Tomen** [comment]
Alright, so I created a proposal of how this could be done here: https://github.com/Tomen/grakn-node/commits/params

However, I cannot test this, since I am on Windows and the Docker Image has not been updated yet. The new params have only been made available with release 1.0.0 and I am still stuck with 0.18.0. So I cannot verify that that this works yet.

It is either possible that someone with a running 1.0.0 installation tests this or I can do this once the appropriate Docker image becomes available.

Things still open until this is tested:
- update unit tests
- update readme

**Comment by idealley** [comment]
Hello,

Your changes look nice. I will try to test them tomorrow. To let you know.

**Comment by idealley** [comment]
As a quick feedback, I have taken your code and simply ran:

```
npm run unit-test
```

There are some test that are failing. I did not investigate further.

**Comment by marco-scoppetta** [comment]
Hi @Tomen,

thank you again for your interest in this Grakn client.
I took inspiration from your PR and updated the client with the possibility to set the `multi` param.
[Here](https://github.com/graknlabs/grakn-node/commit/3e0f75bab1b6c891f20db557db5849e4e12e1af2) you can see the commit.

The new version is available in the npm-registry: [grakn 0.1.1](https://www.npmjs.com/package/grakn).


 DEV NOTES:

The main differences with your PR are:
 - there is no need to set default values on the client side, since in Grakn endpoint we already have default values in case a parameter is missing in the request
- the keyspace is only accepted in the constructor so that you end up having a new Grakn graph for each keyspace, so that you don't need to pass the keyspace as a param every time you want to execute a query on a given graph

Let me know if you have any question,

thank you again!!

Marco

**Comment by idealley** [comment]
Thank you @marco-scoppetta
